//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMONIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogService
    {
        public int Id { get; set; }
        public string TYPE { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> DataTime { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
